### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by pzoloprotonmail** [vmware/vsphere-automation-sdk-rest#41]
Broken link on readme file and https://code.vmware.com/samples/2562/vsphere-automation-rest-api-postman-resources-and-samples

"vSphere-Automation-Rest-Resources.postman_collection.json provides the individual API resources. They are standalone requests that you can execute or use to build up an end to end workflow." 

Points to: 

https://github.com/vmware/vsphere-automation-sdk-rest/blob/master/samples/postman/vSphere-Automation-Rest-Resources.postman_collection.json

It should point to: 

https://github.com/vmware/vsphere-automation-sdk-rest/blob/master/samples/postman/vSphere-Automation-REST-Resources.postman_collection.json

Rest vs REST

**Comment by jrgarcia** [comment]
This has been fixed with [this commit](https://github.com/vmware/vsphere-automation-sdk-rest/commit/f1c238e5f7d14a5afa443a27e1c08f4f1375bd48). I'm not sure how long it will take for the change to show up on VMware {code}, but it will pick up this change at some point. Thanks for the letting me know!
